# Generated by Django 2.2 on 2022-07-05 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='logo1.png', upload_to=''),
        ),
    ]
